version: '3.9'
services:

  fluent:
    image: fluent

    ports:
      - 24224:24224

    networks:
      backend:


  mongo:
    image: mongo:4

    deploy:
      mode: replicated
      replicas: 1

    command: mongod --auth

    environment:
      MONGO_INITDB_ROOT_USERNAME: dev
      MONGO_INITDB_ROOT_PASSWORD: 1234567890
      MONGO_INITDB_DATABASE: dev
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null

    depends_on:
      - fluent

    networks:
      backend:


  mongo-express:
    image: mongo-express

    deploy:
      replicas: 1

    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: dev
      ME_CONFIG_MONGODB_ADMINPASSWORD: 1234567890

    ports:
      - 8081:8081

    depends_on:
      - mongo

    hostname: express

    # logging:
    #   driver: fluentd
    #   options:
    #     tag: "mongo.{{.Config.Hostname}}"
    #     fluentd-address: 127.0.0.1:24224
  
    networks:
      backend: null

networks:
  backend:
